---
name: "Action"
rule_text: |
  “Action” is a type of triggered ability. Players are permitted
  to trigger action abilities during their turn, or by request
  during other players’ turns.
related:
  - Ability
  - Player Turn
  - Triggered Ability
