package manualcards

import "marvelbot/card"

var ManualCards = []*card.MarvelCDBCard{
	&card.MarvelCDBCard{
		TypeCode:    "obligation",
		Position:    53,
		Name:        "Crisis on Halfworld",
		DoubleSided: false,
		ImageSrc:    "images/16053.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    54,
		Name:        "Vendetta",
		DoubleSided: false,
		ImageSrc:    "images/16054.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    55,
		Name:        "Blackjack O'Hare",
		DoubleSided: false,
		ImageSrc:    "images/16055.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		Position:    56,
		Name:        "Blackjack's Bazooka",
		DoubleSided: false,
		ImageSrc:    "images/16056.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    57,
		Name:        "Planetary Invasion",
		DoubleSided: false,
		ImageSrc:    "images/16057.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    58,
		Name:        "Drang",
		DoubleSided: false,
		ImageSrc:    "images/16058.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    59,
		Name:        "Drang",
		DoubleSided: false,
		ImageSrc:    "images/16059.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    60,
		Name:        "Drang",
		DoubleSided: false,
		ImageSrc:    "images/16060.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     61,
		Name:         "Terrestrial Invasion",
		DoubleSided:  true,
		ImageSrc:     "images/16061b.png",
		BackImageSrc: "images/16061a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     62,
		Name:         "Protect the Planet",
		DoubleSided:  true,
		ImageSrc:     "images/16062b.png",
		BackImageSrc: "images/16062a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "environment",
		Position:    63,
		Name:        "Badoon Ship",
		DoubleSided: false,
		ImageSrc:    "images/16063.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		Position:    64,
		Name:        "Drang's Spear",
		DoubleSided: false,
		ImageSrc:    "images/16064.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    65,
		Name:        "Badoon Engineer",
		DoubleSided: false,
		ImageSrc:    "images/16065.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    66,
		Name:        "Blockade",
		DoubleSided: false,
		ImageSrc:    "images/16066.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    67,
		Name:        "Bombardment",
		DoubleSided: false,
		ImageSrc:    "images/16067.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    68,
		Name:        "Oppressive Armada",
		DoubleSided: false,
		ImageSrc:    "images/16068.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    69,
		Name:        "Spatial Positioning",
		DoubleSided: false,
		ImageSrc:    "images/16069.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    70,
		Name:        "Collector",
		DoubleSided: false,
		ImageSrc:    "images/16070.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    71,
		Name:        "Collector",
		DoubleSided: false,
		ImageSrc:    "images/16071.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    72,
		Name:        "Collector",
		DoubleSided: false,
		ImageSrc:    "images/16072.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     73,
		Name:         "The Grand Collection",
		DoubleSided:  true,
		ImageSrc:     "images/16073b.png",
		BackImageSrc: "images/16073a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		Position:    74,
		Name:        "Biogram Image",
		DoubleSided: false,
		ImageSrc:    "images/16074.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    75,
		Name:        "Monark Starstalker",
		DoubleSided: false,
		ImageSrc:    "images/16075.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    76,
		Name:        "Inconspicuous Box",
		DoubleSided: false,
		ImageSrc:    "images/16076.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    77,
		Name:        "View the Cosmos",
		DoubleSided: false,
		ImageSrc:    "images/16077.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    78,
		Name:        "Stay Awhile",
		DoubleSided: false,
		ImageSrc:    "images/16078.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "villain",
		Position:     80,
		Name:         "Collector",
		DoubleSided:  true,
		ImageSrc:     "images/16080b.png",
		BackImageSrc: "images/16080a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "villain",
		Position:     81,
		Name:         "Collector",
		DoubleSided:  true,
		ImageSrc:     "images/16081b.png",
		BackImageSrc: "images/16081a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     82,
		Name:         "The Missing Milano",
		DoubleSided:  true,
		ImageSrc:     "images/16082b.png",
		BackImageSrc: "images/16082a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     83,
		Name:         "Lost in the Museum",
		DoubleSided:  true,
		ImageSrc:     "images/16083b.png",
		BackImageSrc: "images/16083a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     84,
		Name:         "The Great Escape",
		DoubleSided:  true,
		ImageSrc:     "images/16084b.png",
		BackImageSrc: "images/16084a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "environment",
		Position:     85,
		Name:         "Library Labyrinth",
		DoubleSided:  true,
		ImageSrc:     "images/16085b.png",
		BackImageSrc: "images/16085a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "environment",
		Position:     85,
		Name:         "Museum Ship",
		DoubleSided:  true,
		ImageSrc:     "images/16085a.png",
		BackImageSrc: "images/16085b.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    86,
		Name:        "\"I Have You Now!\"",
		DoubleSided: false,
		ImageSrc:    "images/16086.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    87,
		Name:        "Impossible Geometry",
		DoubleSided: false,
		ImageSrc:    "images/16087.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    88,
		Name:        "Nebula",
		DoubleSided: false,
		ImageSrc:    "images/16088.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    89,
		Name:        "Nebula",
		DoubleSided: false,
		ImageSrc:    "images/16089.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    90,
		Name:        "Nebula",
		DoubleSided: false,
		ImageSrc:    "images/16090.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     91,
		Name:         "The Art of Evasion",
		DoubleSided:  true,
		ImageSrc:     "images/16091b.png",
		BackImageSrc: "images/16091a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     92,
		Name:         "Warp Drive Initiated",
		DoubleSided:  true,
		ImageSrc:     "images/16092b.png",
		BackImageSrc: "images/16092a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "environment",
		Position:    93,
		Name:        "Nebula's Ship",
		DoubleSided: false,
		ImageSrc:    "images/16093.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "technique",
		Position:    94,
		Name:        "Cutthroat Ambition",
		DoubleSided: false,
		ImageSrc:    "images/16094.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "technique",
		Position:    95,
		Name:        "Evasive Maneuvering",
		DoubleSided: false,
		ImageSrc:    "images/16095.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "technique",
		Position:    96,
		Name:        "Unyielding Persistence",
		DoubleSided: false,
		ImageSrc:    "images/16096.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "technique",
		Position:    97,
		Name:        "Weapon Mastery",
		DoubleSided: false,
		ImageSrc:    "images/16097.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "technique",
		Position:    98,
		Name:        "Wide Stance",
		DoubleSided: false,
		ImageSrc:    "images/16098.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    99,
		Name:        "Lethal Intent",
		DoubleSided: false,
		ImageSrc:    "images/16099.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    100,
		Name:        "Barrel Roll",
		DoubleSided: false,
		ImageSrc:    "images/16100.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    101,
		Name:        "Combat Ready",
		DoubleSided: false,
		ImageSrc:    "images/16101.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    102,
		Name:        "Ruthless",
		DoubleSided: false,
		ImageSrc:    "images/16102.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    103,
		Name:        "Ronan the Accuser",
		DoubleSided: false,
		ImageSrc:    "images/16103.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    104,
		Name:        "Ronan the Accuser",
		DoubleSided: false,
		ImageSrc:    "images/16104.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "villain",
		Position:    105,
		Name:        "Ronan the Accuser",
		DoubleSided: false,
		ImageSrc:    "images/16105.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     106,
		Name:         "Interception Imminent",
		DoubleSided:  true,
		ImageSrc:     "images/16106b.png",
		BackImageSrc: "images/16106a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "main_scheme",
		Position:     107,
		Name:         "\"Take What Is Mine\"",
		DoubleSided:  true,
		ImageSrc:     "images/16107b.png",
		BackImageSrc: "images/16107a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "environment",
		Position:    108,
		Name:        "Kree Command Ship",
		DoubleSided: false,
		ImageSrc:    "images/16108.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		Position:    109,
		Name:        "Universal Weapon",
		DoubleSided: false,
		ImageSrc:    "images/16109.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		Position:    110,
		Name:        "Fanaticism",
		DoubleSided: false,
		ImageSrc:    "images/16110.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    111,
		Name:        "Cut the Power",
		DoubleSided: false,
		ImageSrc:    "images/16111.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    112,
		Name:        "Pincer Maneuver",
		DoubleSided: false,
		ImageSrc:    "images/16112.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		Position:    113,
		Name:        "Superior Tactics",
		DoubleSided: false,
		ImageSrc:    "images/16113.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    114,
		Name:        "Single-Minded Fury",
		DoubleSided: false,
		ImageSrc:    "images/16114.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    115,
		Name:        "Kree Physiology",
		DoubleSided: false,
		ImageSrc:    "images/16115.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		Position:    116,
		Name:        "\"You Stand Accused!\"",
		DoubleSided: false,
		ImageSrc:    "images/16116.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    117,
		Name:        "Badoon Assassin",
		DoubleSided: false,
		ImageSrc:    "images/16117.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    118,
		Name:        "Badoon Grunt",
		DoubleSided: false,
		ImageSrc:    "images/16118.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    119,
		Name:        "Badoon Lieutenant",
		DoubleSided: false,
		ImageSrc:    "images/16119.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    120,
		Name:        "Badoon Sentry",
		DoubleSided: false,
		ImageSrc:    "images/16120.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		Position:    121,
		Name:        "Badoon Warlord",
		DoubleSided: false,
		ImageSrc:    "images/16121.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		SetName:     "Galactic Artifacts",
		Position:    122,
		Name:        "Cloak of Hercules",
		DoubleSided: false,
		ImageSrc:    "images/16122.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		SetName:     "Galactic Artifacts",
		Position:    123,
		Name:        "Obedience Potion",
		DoubleSided: false,
		ImageSrc:    "images/16123.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		SetName:     "Galactic Artifacts",
		Position:    124,
		Name:        "The Beyonder's Blazer",
		DoubleSided: false,
		ImageSrc:    "images/16124.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		SetName:     "Galactic Artifacts",
		Position:    125,
		Name:        "The Poison",
		DoubleSided: false,
		ImageSrc:    "images/16125.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		SetName:     "Galactic Artifacts",
		Position:    126,
		Name:        "Vandarian Power Wand",
		DoubleSided: false,
		ImageSrc:    "images/16126.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Galactic Artifacts",
		Position:    127,
		Name:        "Hujahdarian Monarch Egg",
		DoubleSided: false,
		ImageSrc:    "images/16127.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Galactic Artifacts",
		Position:    128,
		Name:        "Magical Teapot",
		DoubleSided: false,
		ImageSrc:    "images/16128.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Galactic Artifacts",
		Position:    129,
		Name:        "Philosopher's Stone",
		DoubleSided: false,
		ImageSrc:    "images/16129.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Galactic Artifacts",
		Position:    130,
		Name:        "Crystal Ball",
		DoubleSided: false,
		ImageSrc:    "images/16130.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		SetName:     "Kree Militants",
		Position:    131,
		Name:        "Kree Combat Armor",
		DoubleSided: false,
		ImageSrc:    "images/16131.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Kree Militants",
		Position:    132,
		Name:        "Kree Commando",
		DoubleSided: false,
		ImageSrc:    "images/16132.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Kree Militants",
		Position:    133,
		Name:        "Kree Lieutenant",
		DoubleSided: false,
		ImageSrc:    "images/16133.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Kree Militants",
		Position:    134,
		Name:        "Kree Private",
		DoubleSided: false,
		ImageSrc:    "images/16134.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Menagerie Medley",
		Position:    135,
		Name:        "Psionic Ghost",
		DoubleSided: false,
		ImageSrc:    "images/16135.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Menagerie Medley",
		Position:    136,
		Name:        "Servant Bot",
		DoubleSided: false,
		ImageSrc:    "images/16136.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Menagerie Medley",
		Position:    137,
		Name:        "Starshark",
		DoubleSided: false,
		ImageSrc:    "images/16137.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Space Pirates",
		Position:    138,
		Name:        "Pirate Commander",
		DoubleSided: false,
		ImageSrc:    "images/16138.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Space Pirates",
		Position:    139,
		Name:        "Pirate Lackey",
		DoubleSided: false,
		ImageSrc:    "images/16139.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Space Pirates",
		Position:    140,
		Name:        "Sound the Alarms",
		DoubleSided: false,
		ImageSrc:    "images/16140.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Space Pirates",
		Position:    141,
		Name:        "Honor Among Thieves",
		DoubleSided: false,
		ImageSrc:    "images/16141.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "support",
		SetName:     "Ship Command",
		Position:    142,
		Name:        "Milano",
		DoubleSided: false,
		ImageSrc:    "images/16142.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "environment",
		SetName:     "Ship Command",
		Position:    143,
		Name:        "Rogue Vessel",
		DoubleSided: false,
		ImageSrc:    "images/16143.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Ship Command",
		Position:    144,
		Name:        "Cannonade",
		DoubleSided: false,
		ImageSrc:    "images/16144.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Ship Command",
		Position:    145,
		Name:        "Blind Side",
		DoubleSided: false,
		ImageSrc:    "images/16145.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		SetName:     "Ship Command",
		Position:    146,
		Name:        "Hull Breach",
		DoubleSided: false,
		ImageSrc:    "images/16146.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "side_scheme",
		SetName:     "Ship Command",
		Position:    147,
		Name:        "Power Siphon",
		DoubleSided: false,
		ImageSrc:    "images/16147.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		SetName:     "Ship Command",
		Position:    148,
		Name:        "Special Delivery",
		DoubleSided: false,
		ImageSrc:    "images/16148.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "attachment",
		SetName:     "Power Stone",
		Position:    149,
		Name:        "Power Stone",
		DoubleSided: false,
		ImageSrc:    "images/16149.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    150,
		Name:        "Brainstorm",
		DoubleSided: false,
		ImageSrc:    "images/16150.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    151,
		Name:        "By Any Means",
		DoubleSided: false,
		ImageSrc:    "images/16151.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    152,
		Name:        "Contingency Plan",
		DoubleSided: false,
		ImageSrc:    "images/16152.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    153,
		Name:        "In Defiance",
		DoubleSided: false,
		ImageSrc:    "images/16153.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    154,
		Name:        "Calculate the Odds",
		DoubleSided: false,
		ImageSrc:    "images/16154.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    155,
		Name:        "Creative Solution",
		DoubleSided: false,
		ImageSrc:    "images/16155.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    156,
		Name:        "Grapple",
		DoubleSided: false,
		ImageSrc:    "images/16156.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    157,
		Name:        "Wing It",
		DoubleSided: false,
		ImageSrc:    "images/16157.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    158,
		Name:        "Close Call",
		DoubleSided: false,
		ImageSrc:    "images/16158.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    159,
		Name:        "Defy Danger",
		DoubleSided: false,
		ImageSrc:    "images/16159.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    160,
		Name:        "In Harm's Way",
		DoubleSided: false,
		ImageSrc:    "images/16160.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    161,
		Name:        "Take the Fight to Them",
		DoubleSided: false,
		ImageSrc:    "images/16161.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    162,
		Name:        "Armor Plating",
		DoubleSided: false,
		ImageSrc:    "images/16162.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    163,
		Name:        "Heavy Cannon",
		DoubleSided: false,
		ImageSrc:    "images/16163.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    164,
		Name:        "Hyper Thrusters",
		DoubleSided: false,
		ImageSrc:    "images/16164.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    165,
		Name:        "Reactor Core",
		DoubleSided: false,
		ImageSrc:    "images/16165.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    166,
		Name:        "Ardent Resolve",
		DoubleSided: false,
		ImageSrc:    "images/16166.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    167,
		Name:        "Onrush",
		DoubleSided: false,
		ImageSrc:    "images/16167.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    168,
		Name:        "Safeguard",
		DoubleSided: false,
		ImageSrc:    "images/16168.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    169,
		Name:        "Sure Gamble",
		DoubleSided: false,
		ImageSrc:    "images/16169.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    170,
		Name:        "Cargo Hold",
		DoubleSided: false,
		ImageSrc:    "images/16170.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    171,
		Name:        "Mounted Laser",
		DoubleSided: false,
		ImageSrc:    "images/16171.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    172,
		Name:        "Navigation Column",
		DoubleSided: false,
		ImageSrc:    "images/16172.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "upgrade",
		SetName:     "The Market",
		Position:    173,
		Name:        "Targeting Screen",
		DoubleSided: false,
		ImageSrc:    "images/16173.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    174,
		Name:        "Grand Strategy",
		DoubleSided: false,
		ImageSrc:    "images/16174.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    175,
		Name:        "Power Unleashed",
		DoubleSided: false,
		ImageSrc:    "images/16175.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    176,
		Name:        "Tried and True",
		DoubleSided: false,
		ImageSrc:    "images/16176.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "event",
		SetName:     "The Market",
		Position:    177,
		Name:        "Triple Threat",
		DoubleSided: false,
		ImageSrc:    "images/16177.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "side_scheme",
		Position:     178,
		Name:         "Badoon Blitz",
		DoubleSided:  false,
		ImageSrc:     "images/16178b.png",
		BackImageSrc: "images/16178a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "side_scheme",
		Position:     179,
		Name:         "Gallery of Splendor",
		DoubleSided:  false,
		ImageSrc:     "images/16179b.png",
		BackImageSrc: "images/16179a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "side_scheme",
		Position:     180,
		Name:         "\"There Is No Escape\"",
		DoubleSided:  false,
		ImageSrc:     "images/16180b.png",
		BackImageSrc: "images/16180a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "side_scheme",
		Position:     181,
		Name:         "Guerilla Tactics",
		DoubleSided:  false,
		ImageSrc:     "images/16181b.png",
		BackImageSrc: "images/16181a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:     "side_scheme",
		Position:     182,
		Name:         "Kree Supremacy",
		DoubleSided:  false,
		ImageSrc:     "images/16182b.png",
		BackImageSrc: "images/16182a.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Badoon Headhunter",
		Position:    183,
		Name:        "Badoon Headhunter",
		DoubleSided: false,
		ImageSrc:    "images/16183.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		SetName:     "Badoon Headhunter",
		Position:    184,
		Name:        "On the Hunt",
		DoubleSided: false,
		ImageSrc:    "images/16184.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		SetName:     "Badoon Headhunter",
		Position:    185,
		Name:        "Dead to Rights",
		DoubleSided: false,
		ImageSrc:    "images/16185.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "minion",
		SetName:     "Badoon Headhunter",
		Position:    186,
		Name:        "Headhunter's Henchman",
		DoubleSided: false,
		ImageSrc:    "images/16186.png",
	},
	&card.MarvelCDBCard{
		TypeCode:    "treachery",
		SetName:     "Badoon Headhunter",
		Position:    187,
		Name:        "Fugitive Recovery",
		DoubleSided: false,
		ImageSrc:    "images/16187.png",
	},
}
